package:
  name: elektronn
  version: 1.0.13

source:
  path: ./

requirements:
  build:
    - python >=2.7,<3
    - setuptools >=18.0
    - cython >=0.23
    - h5py >=2.5
    - matplotlib >=1.5
    - numpy >=1.8
    - scikit-learn >=0.14
    - scipy >=0.17.1
    - theano >=0.7
    - gcc >=4.8

  run:
    - python >=2.7,<3
    - cython >=0.23
    - h5py >=2.5
    - matplotlib >=1.5
    - numpy >=1.8
    - scikit-learn >=0.14,<0.20
    - scipy >=0.17.1
    - theano >=0.7

about:
  home: http://www.elektronn.org/
  license: GPLv3
  license_file: LICENSE.txt
