package:
  name: elektronn
  version: 1.0.7

source:
  path: ./

requirements:
  build:
    - python 2.7*
    - setuptools
    - cython
    - h5py
    - matplotlib
    - numpy
    - scikit-learn
    - scipy
    - theano

  run:
    - python 2.7*
    - h5py
    - matplotlib
    - numpy
    - scikit-learn
    - scipy
    - theano

about:
  home: http://www.elektronn.org/
  license: GPLv3
  license_file: LICENSE.txt
